import type { Metadata } from "next";
import { Inter, Dela_Gothic_One } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const delaGothic = Dela_Gothic_One({
  variable: "--font-Dela",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={`${inter.variable} ${delaGothic.variable} antialiased bg-[#01060f]`}
      >
        <Header />
        <main className="relative ">
          <div className="pointer-events-none absolute inset-0 -z-10 bg-white/5 bg-[linear-gradient(to_right,#d9d9d980_1px,transparent_1px),linear-gradient(to_bottom,#d9d9d980_1px,transparent_1px)] bg-size-[122px_122px]" />
          <div className="relative z-10">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
